name: Tests
on: [push]
env:
  IMAGE_NAME: danack_phpopendocs
jobs:
  # unit_tests:
  #   name: Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master
  #     - name: Perform phpunit tests
  #       uses: ./containers/run_php_tests
  code_style:
    name: Code Style Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Set status pending
        uses: ouzi-dev/commit-status-updater@v1.1.0
      - name: Checkout
        uses: actions/checkout@master
      - name: Analyze code style
        uses: ./containers/run_php_codesniffer
      - if: ${{ always() }}
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          status: "${{ job.status }}"

